const images={Kerala:'https://wallpaperaccess.com/full/1635200.jpg',Munnar:'https://cdn.kimkim.com/files/a/images/eacac416ec738fc51b9193d24cd3cc71d55b1f15/big-c1314a2d84ff6f02a0889fc5b82d1ecb.jpg',Varkala:'https://seoimgak.mmtcdn.com/blog/sites/default/files/images/celebration-of-gods-own-country-beach.jpg'};
const places=[{name:'Munnar',region:'KERALA · THE HILLS',title:'A thousand shades of green.',caption:'Tea Museum, Mattupetty and a real hill-country stay.',tag:'OFF THE MAP',type:'offbeat'},{name:'Varkala',region:'KERALA · THE COAST',title:'Chase a slower sunset.',caption:'Cliff walks, Kappil and a coastal place to stay.',tag:'COASTAL STATE OF MIND',type:'coast'},{name:'Kerala',region:'FORT KOCHI · THE OLD PORT',title:'Let the stories find you.',caption:'A Kochi heritage route, with Brunton Boatyard as a stay option.',tag:'THE ART OF SLOW',type:'slow'}];
const $=s=>document.querySelector(s);
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>'₹'+Math.round(v).toLocaleString('en-IN');
const external=(url,text,cls='source-link')=>`<a class="${cls}" href="${escapeHTML(url)}" target="_blank" rel="noopener noreferrer">${escapeHTML(text)} ↗</a>`;
const maps=(query)=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(query);
let destination='Kerala',tab='Plan',queue=[],generating=false,budget=15000,routeMemory={},activeRegion='all',trailState='kerala',trailOnlySaved=false;
const current=()=>stateByName(destination);
function tripState(){const id=current().id;if(!routeMemory[id])routeMemory[id]={saved:[],swaps:{},hotel:0,late:false,booked:false,checked:[],budget:{nightly:null,arrival:null,food:800,local:1000,activities:500,extra:0}};return routeMemory[id]}
const stopList=s=>[...s.days.flatMap(d=>d.stops),...(s.extras||[])];
const stopById=(s,id)=>stopList(s).find(p=>p.id===id);
function notify(msg){$('#toast').textContent=msg;$('#toast').classList.add('visible');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500)}
function sheet(html){if($('#sheet').open)$('#sheet').close();$('#sheet-content').innerHTML=html;$('#sheet').showModal()}
$('#sheet').addEventListener('click',e=>{if(e.target===$('#sheet'))$('#sheet').close()});
function showView(view){['discover','trip','trails'].forEach(v=>$('#'+v).hidden=v!==view);document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));if(view==='trip')renderTrip();if(view==='trails')renderTrails();window.scrollTo({top:0,behavior:'instant'})}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('.brand').onclick=e=>{e.preventDefault();showView('discover')};
function browseIndia(){showView('discover');$('#india').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});$('#state-search').focus({preventScroll:true})}
function card(p){return `<article class="destination"><button style="width:100%;text-align:left;padding:0" onclick="choose('${p.name}')"><div class="destination-photo"><img src="${images[p.name]}" alt="${p.name==='Munnar'?'Tea plantations in Munnar':p.name==='Varkala'?'Varkala beach and cliffs':'Kerala backwaters; the itinerary explores Kochi'}" loading="lazy"><span class="photo-tag">${p.tag}</span></div><div class="destination-body"><small>${p.region}</small><h3>${p.title}</h3><p>${p.caption}</p><div class="card-foot"><span>3-day route · Real places & stays</span><span>↗</span></div></div></button></article>`}
function filter(el,type){document.querySelectorAll('.filters button').forEach(b=>b.classList.remove('selected'));el.classList.add('selected');$('#destination-grid').innerHTML=places.filter(p=>type==='all'||p.type===type).map(card).join('')}
filter($('.filters button'),'all');$('#hero-image').src=images.Kerala;
$('#state-picker').innerHTML='<option value="">All 28 states · Pick one</option>'+INDIA_STATES.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');
$('#state-picker').onchange=()=>{const s=INDIA_STATES.find(s=>s.id===$('#state-picker').value);if(s)$('#intent').value=`${s.name}: ${s.base} and nearby places`};
function renderStateDirectory(){const q=$('#state-search').value.trim().toLowerCase();const results=INDIA_STATES.filter(s=>(activeRegion==='all'||s.region===activeRegion)&&[s.name,s.base,s.line,...stopList(s).map(p=>p.name),...(s.further||[]).map(p=>p.name),...(s.food||[]).map(p=>p.name),...s.hotels.map(h=>h.name)].join(' ').toLowerCase().includes(q));$('#state-count').textContent=`${results.length} of 28 states${activeRegion==='all'?'':' · '+activeRegion}`;$('.region-chips').innerHTML=['all','North','South','East','West','Central','Northeast'].map(r=>`<button aria-pressed="${r===activeRegion}" class="${r===activeRegion?'selected':''}" onclick="setRegion('${r}')">${r==='all'?'All India':r}</button>`).join('');$('#state-grid').innerHTML=results.length?results.map(s=>`<article class="state-card" data-state="${s.id}"><button class="state-open" onclick="openStateCard('${s.name}')"><div class="state-image"><img src="${escapeHTML(s.photo.url)}" alt="${escapeHTML(s.photo.caption)}" loading="lazy" width="640" height="420"><span class="state-region">${s.region}</span></div><div class="state-copy"><h3>${s.name}</h3><p>${s.base}${s.name==='Manipur'?' · Advisory':''}</p><div class="state-card-bottom"><span>${s.hotels.length} stays · ${s.food.length} food spot${s.food.length===1?'':'s'}</span><span aria-hidden="true">↗</span></div></div></button><div class="state-credit">${photoCredit(s.photo)}</div></article>`).join(''):'<div class="empty-state"><h3>No states match that search.</h3><p>Try a state such as Rajasthan, a city such as Mysuru, or clear the region filter.</p><button class="primary" onclick="clearStateSearch()">Show all 28 states</button></div>'}
function setRegion(r){activeRegion=r;$('#region-filter').value=r;renderStateDirectory()}
function clearStateSearch(){$('#state-search').value='';setRegion('all')}
$('#state-search').oninput=renderStateDirectory;$('#region-filter').onchange=e=>setRegion(e.target.value);renderStateDirectory();
function choose(name){const s=stateByName(name);if(!s){notify('Please choose a state from the collection.');return}destination=s.name;$('#state-picker').value=(s.stateName?stateByName(s.stateName):s).id;$('#intent').value=`${s.name}: ${s.base} and nearby places`;tab='Plan';$('#trip-days').value=$('#days').value;setTripHash();showView('trip')}
const aliases={'vizag':'Andhra Pradesh','visakhapatnam':'Andhra Pradesh','itanagar':'Arunachal Pradesh','guwahati':'Assam','bodhgaya':'Bihar','bodh gaya':'Bihar','raipur':'Chhattisgarh','panaji':'Goa','ahmedabad':'Gujarat','kurukshetra':'Haryana','shimla':'Himachal Pradesh','ranchi':'Jharkhand','mysore':'Karnataka','mysuru':'Karnataka','bengaluru':'Karnataka','bangalore':'Karnataka','kochi':'Kerala','cochin':'Kerala','bhopal':'Madhya Pradesh','mumbai':'Maharashtra','imphal':'Manipur','shillong':'Meghalaya','aizawl':'Mizoram','kohima':'Nagaland','bhubaneswar':'Odisha','orissa':'Odisha','amritsar':'Punjab','jaipur':'Rajasthan','gangtok':'Sikkim','chennai':'Tamil Nadu','hyderabad':'Telangana','agartala':'Tripura','varanasi':'Uttar Pradesh','dehradun':'Uttarakhand','kolkata':'West Bengal','calcutta':'West Bengal'};
function matchRoute(q){let text=q.toLowerCase().replace(/\bfrom\s+(bangalore|bengaluru|mumbai|chennai|hyderabad|kolkata|delhi|kochi)\b/g,'');const names=ALL_ROUTES.filter(s=>new RegExp('\\b'+s.name.toLowerCase()+'\\b').test(text));if(names.length)return names.sort((a,b)=>text.lastIndexOf(b.name.toLowerCase())-text.lastIndexOf(a.name.toLowerCase()))[0];const matched=Object.entries(aliases).filter(([a])=>new RegExp('\\b'+a+'\\b').test(text));if(matched.length)return stateByName(matched.sort((a,b)=>text.lastIndexOf(b[0])-text.lastIndexOf(a[0]))[0][1]);return null}
async function generate(){if(generating)return;const q=$('#intent').value.trim();let s=matchRoute(q);if(!s&&!q&&$('#state-picker').value)s=INDIA_STATES.find(s=>s.id===$('#state-picker').value);if(!s&&/green|quiet|slow|backwater/i.test(q))s=stateByName('Kerala');if(!s){sheet('<h2>Choose a starting point.</h2><p>This collection has a researched route for each of India’s 28 states. Choose a state above, or search the collection by city or landmark.</p><button class="primary wide" onclick="document.querySelector(\'#sheet\').close();browseIndia()">Explore all 28 states ↗</button>');return}generating=true;const b=$('#generate');b.disabled=true;for(const text of [`Opening the ${s.name} route…`,'Gathering the place and hotel sources…']){b.textContent=text;await new Promise(r=>setTimeout(r,400))}b.innerHTML='Find my escape <span>↗</span>';b.disabled=false;generating=false;choose(s.name);notify(`${s.base} route ready. Sources and real stays included.`)}
function setTripHash(){const hash=`#trip=${current().id}&days=${$('#days').value}`;history.replaceState(null,'',hash)}
function loadTripHash(){const params=new URLSearchParams(location.hash.slice(1));const route=ALL_ROUTES.find(s=>s.id===params.get('trip'));if(route){const d=params.get('days');if(['2','3','4','7'].includes(d))$('#days').value=d;choose(route.name)}}
$('#trip-days').onchange=()=>{$('#days').value=$('#trip-days').value;setTripHash();renderTrip()};
async function copyTripLink(){try{await navigator.clipboard.writeText(location.href);notify('Trip link copied. It opens this route and duration.')}catch{sheet(`<h2>Your trip link</h2><label class="form-field">Copy this link<input value="${escapeHTML(location.href)}" readonly onclick="this.select()"></label>`)}}
function tune(){sheet(`<span class="eyebrow">MAKE IT YOUR KIND OF TRIP</span><h2>A few little preferences.</h2><label class="form-field">Budget ceiling <strong id="budget-label">${money(budget)}</strong><input id="budget-input" type="range" min="8000" max="100000" step="500" value="${budget}" oninput="document.querySelector('#budget-label').textContent='₹'+Number(this.value).toLocaleString('en-IN')"></label><label class="form-field">Your pace<select id="pace">${['Balanced','Chill','Packed'].map(p=>`<option ${p===(window.pace||'Balanced')?'selected':''}>${p}</option>`).join('')}</select></label><label class="form-field">Travellers<select id="travellers">${[1,2,3,4].map(n=>`<option value="${n}" ${n===(window.travellerCount||1)?'selected':''}>${n} traveller${n>1?'s':''}</option>`).join('')}</select></label><button class="primary wide" onclick="savePreferences()">Sounds like me ✓</button>`)}
function savePreferences(){budget=Number($('#budget-input').value);window.pace=$('#pace').value;window.travellerCount=Number($('#travellers').value);$('#sheet').close();if(!$('#trip').hidden)renderTrip();notify('Preferences saved. Budget limits apply to your worksheet.')}
function routeDays(){const s=current(),m=tripState(),length=Number($('#days').value);const days=s.days.map(d=>({...d,stops:d.stops.map(p=>({...p}))}));const spare=days[2].stops.length>1?days[2].stops.pop():null;
 for(const d of days)d.stops=d.stops.map(p=>m.swaps[p.id]?({...stopById(s,m.swaps[p.id])}):p);
 const visibleIds=new Set(days.flatMap(d=>d.stops).map(p=>p.id));for(const id of m.saved){if(!visibleIds.has(id)){const p=stopById(s,id);if(p){days[1].stops.push({...p});visibleIds.add(id)}}}
 if(length===2){const selected=days.slice(0,2);selected[1].travel+=' Two-day highlights omit the third-day outing.';return delayed(selected,m)}
 if(length===3)return delayed(days,m);
 const expanded=[];if(length===4){expanded.push({title:'Arrive and settle in',travel:`Arrive in ${s.base}; check in and leave the rest of the day free.`,stops:[]},...days)}else{expanded.push({title:'Arrive and settle in',travel:`Allow a full arrival day in ${s.base}.`,stops:[]});for(const d of days){expanded.push(d);expanded.push({title:'A day at your own pace',travel:`Stay in ${s.base}. Keep this day free for rest, local meals, or a return to a favourite spot.`,stops:[]})}}
 return delayed(expanded,m)
}
function delayed(days,m){if(!m.late)return days;const first=days.findIndex(d=>d.stops.length>0);if(first<0||first>=days.length-1)return days;const moved=days[first].stops.pop();days[first].travel+=' Late-start version: the last stop moves to tomorrow.';days[first+1].stops.unshift({...moved,moved:true});return days}
function budgetValues(){const b=tripState().budget,d=Number($('#days').value),people=window.travellerCount||1,nights=d-1;const stay=b.nightly===null?null:b.nightly*nights;const local=b.local*d,food=b.food*d*people,activities=b.activities*d*people,extra=b.extra*d;const subtotal=(stay||0)+(b.arrival||0)+local+food+activities+extra;return {stay,local,food,activities,extra,arrival:b.arrival,buffer:Math.ceil(subtotal*.1),total:Math.ceil(subtotal*1.1),complete:stay!==null&&b.arrival!==null,nights,people}}
function total(){return budgetValues().total}
function sourceBlock(s){return `<details class="sources-panel"><summary>Sources & planning notes <span>Checked ${INDIA_CHECKED}</span></summary><p>Places are drawn from tourism sources; the order is an editorial suggestion. Opening days, admission, road access and hotel availability still need checking for your dates.</p>${s.sources.map((url,i)=>external(url,`Place guide ${i+1} · ${new URL(url).hostname}`)).join('')}<p>Stay listings are supported by the property’s website or a government accommodation directory. Listing a hotel does not mean it fits your budget or is available.</p>${s.hotels.map(h=>external(h.url,h.name)).join('')}<p>Food venue and menu sources</p>${(s.food||[]).map(f=>external(f.url,f.name)).join('')}</details>`}
function activity(p,index){const m=tripState();return `<div class="activity" data-stop="${p.id}"><span class="time">${p.moved?'MOVED':index===0?'FIRST STOP':'THEN'}</span><div>${photoFigure(p.photo)}<h3>${escapeHTML(p.name)}${m.saved.includes(p.id)?' <span class="saved-label">SAVED</span>':''}</h3><p>${escapeHTML(p.why)}</p><p class="place-note">${escapeHTML(p.note)}</p><div class="place-links">${external(maps(p.mapQuery),'View on map')}${external(p.source,'Tourism source')}</div><div class="activity-controls"><button onclick="swapActivity('${p.id}')">↻ Swap stop</button><button onclick="pinSpot('${p.id}')">${m.saved.includes(p.id)?'✓ Saved':'＋ Save spot'}</button></div></div></div>`}
function renderTrip(){const s=current(),m=tripState(),d=Number($('#days').value);$('#trip-days').value=String(d);$('#trip-title').innerHTML=`${escapeHTML(s.name)}.<br><em>${escapeHTML(s.base)}, at your pace.</em>`;$('#trip-meta').textContent=`${d} days · ${d-1} nights · ${window.travellerCount||1} traveller${(window.travellerCount||1)>1?'s':''} · ${window.pace||'Balanced'} · Researched route`;
$('.segments').innerHTML=['Plan','Money','Stay','Food','Trails','Go'].map(t=>`<button role="tab" id="tab-${t}" aria-controls="trip-content" aria-selected="${t===tab}" tabindex="${t===tab?0:-1}" class="${t===tab?'selected':''}" onclick="setTab('${t}')">${t==='Trails'?'Places':t}</button>`).join('');$('#trip-content').setAttribute('role','tabpanel');$('#trip-content').setAttribute('aria-labelledby','tab-'+tab);
let html='';if(tab==='Plan'){html=photoFigure(s.photo,'route-photo')+`<div class="route-intro"><span class="eyebrow">${s.region.toUpperCase()} INDIA · BASE: ${escapeHTML(s.base.toUpperCase())}</span><p>${escapeHTML(s.line)}</p><p class="fine">This itinerary starts after you reach ${escapeHTML(s.base)}. Arrival travel is separate. ${d===3?'Two planned stops or fewer on most days, with room for meals and rest.':d===2?'A shortened highlights route; not every stop fits.':'The three-day sightseeing route is spread across a longer stay with explicit free time.'}</p></div>${s.notes?`<div class="route-note ${s.name==='Manipur'?'advisory':''}">${escapeHTML(s.notes)}${s.name==='Manipur'?external('https://www.gov.uk/foreign-travel-advice/india/regional-risks','Read current UK travel advice'):''}</div>`:''}`;html+=routeDays().map((day,i)=>`<section class="day" style="animation-delay:${i*30}ms"><div class="day-heading"><span class="day-number">${String(i+1).padStart(2,'0')}</span><div><small>DAY ${i+1} · ${escapeHTML(s.base.toUpperCase())}</small><h2>${escapeHTML(day.title)}</h2></div></div><p class="day-route">${escapeHTML(day.travel)}</p>${day.stops.map(activity).join('')}${!day.stops.length?'<p class="free-day">No timed activities. Keep this space yours.</p>':''}<div class="overnight">${i<d-1?'☾ Overnight in '+escapeHTML(s.base):'↗ Departure or onward travel'}${i<d-1?`<button onclick="setTab('Stay')">${escapeHTML(s.hotels[m.hotel].name)} ↗</button>`:''}</div></section>`).join('');html+=`<div class="panel"><h2>Make room for a good meal.</h2><p>${s.food?.length||0} sourced food spots for this route.</p><button class="secondary" onclick="setTab('Food')">Explore food spots ↗</button><button class="text-button" onclick="setTab('Trails')">More places in this state ↗</button></div>`+sourceBlock(s)}
if(tab==='Food')html=renderFood(s);if(tab==='Stay')html=renderStays(s);if(tab==='Money')html=renderMoney();if(tab==='Trails')html=`<div class="route-intro"><span class="eyebrow">PLACES IN ${escapeHTML(s.name.toUpperCase())}</span><h2>A detour worth keeping.</h2><p>Save a real place to this itinerary. City stops below can be saved to your route. Further afield ideas need their own travel plan.</p></div>`+discoveryCards(s)+furtherCards(s)+sourceBlock(s);
if(tab==='Go'){const next=routeDays().flatMap(d=>d.stops)[0];html=`<div class="panel"><span class="eyebrow">${m.booked?'DEMO TRIP SAVED':'YOUR TRAVEL COMPANION'}</span><h2>${m.late?'A late start. A softer landing.':'Today, at your pace.'}</h2><p>${m.late?'Your first day’s last stop has moved to the next day. Recheck opening hours and the route before following the revised order.':'First planned stop: '+escapeHTML(next?.name||s.base)+'.'}</p>${next?external(maps(next.mapQuery),'Open the location'):''}<button class="primary wide" onclick="tripState().late=!tripState().late;renderTrip();notify(tripState().late?'Late-start route applied. Review the Plan tab.':'Original route restored.')">${m.late?'Restore original day':'I’m running late'}</button><button class="text-button" onclick="delay()">Simulate a flight delay ↗</button></div><div class="panel"><h2>The little things, sorted.</h2>${['Photo ID and booking confirmations','Confirm entry rules and opening days','Weather-appropriate layers and comfortable shoes','Charger and downloaded tickets'].map((t,i)=>`<label class="packing-item"><input type="checkbox" ${m.checked.includes(i)?'checked':''} onchange="togglePacking(${i},this.checked)">${t}</label>`).join('')}<button class="text-button" onclick="printTrip()">Print / save itinerary ↗</button><button class="text-button" onclick="support()">Talk to a person ↗</button></div>`}
$('#trip-content').innerHTML=html;renderSummary();$('.segments').onkeydown=e=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();const tabs=['Plan','Money','Stay','Food','Trails','Go'];let i=tabs.indexOf(tab);i=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;setTab(tabs[i]);$('#tab-'+tabs[i]).focus()}}
function setTab(t){tab=t;renderTrip()}
function renderSummary(){const s=current(),m=tripState(),v=budgetValues();$('.summary').innerHTML=`<span class="eyebrow">YOUR ESCAPE, TOGETHER</span><h2 id="price">${v.complete?money(v.total):'Your route.<br>Your budget.'}</h2><p>${v.complete?'Your planning estimate · not a live quote':'Real places. Confirm rates for your dates.'}</p><div class="costline"><span>Base</span><b>${escapeHTML(s.base)}</b></div><div class="costline"><span>Length</span><b>${$('#days').value} days / ${v.nights} nights</b></div><div class="costline"><span>Stay choice</span><b>${escapeHTML(s.hotels[m.hotel].name)}</b></div><div class="costline"><span>Your budget ceiling</span><b>${money(budget)}</b></div><button class="primary wide" onclick="setTab('Stay')">Explore real stays ↗</button><button class="secondary wide" onclick="book()">Review whole trip</button><p class="fine">Hotel rates, admission and transport are not live. No bookings or payments are made here.</p><div class="support">✧ Plan with something to go on.<br><span>Sources checked ${INDIA_CHECKED}.</span></div>`}
function renderStays(s){return `<div class="route-intro"><span class="eyebrow">A REAL PLACE TO LAND</span><h2>Stay in ${escapeHTML(s.base)}.</h2><p>${s.hotels.length>1?'Compare these named options':'A named stay option'} for this route. Check the property for rates, room type and cancellation terms.</p></div>`+s.hotels.map((h,i)=>`<article class="panel stay-card"><div class="stay-label"><span>${escapeHTML(h.type)}</span><span>${tripState().hotel===i?'✓ Selected for planning':''}</span></div><h2>${escapeHTML(h.name)}</h2><p>⌖ ${escapeHTML(h.area)}</p><p>Compare the address with your route around ${escapeHTML(s.base)}. Some properties are outside the centre; check transfers before choosing.</p><div class="stay-status"><span>Price & availability</span><strong>Check your dates</strong></div><div class="stay-links">${external(h.url,h.url.includes('.nic.in')?'Official accommodation listing':'Visit official website','secondary')}${external(maps(h.name+', '+h.area),'Find on map','secondary')}</div><button class="primary wide" onclick="tripState().hotel=${i};renderTrip();notify('Stay selected for planning. Nothing is reserved.')">${tripState().hotel===i?'✓ Selected for this trip':'Select this stay'}</button><details class="stay-check"><summary>Before choosing this stay</summary><p>Ask about step-free access, room configuration, taxes, meals, check-in arrangements and the cancellation policy for your rate. No unverified amenities or drawbacks are assumed.</p></details></article>`).join('')+sourceBlock(s)}
function renderMoney(){const b=tripState().budget;return `<div class="panel"><span class="eyebrow">A WORKSHEET, NOT A PRICE PROMISE</span><h2>Make the numbers yours.</h2><p>Enter a nightly room quote and your arrival travel cost. Food, local transport and activity amounts below are editable planning allowances, not researched prices.</p><div class="budget-inputs">${[['nightly','Room / night (one room)',null],['arrival','Return travel to the base (whole group)',null],['food','Food / person / day',800],['local','Local transport / group / day',1000],['activities','Activities / person / day',500]].map(([key,label])=>`<label class="form-field">${label}<input aria-label="${label}" type="number" min="0" max="1000000" step="100" placeholder="Add a quote" value="${b[key]??''}" oninput="updateBudget('${key}',this.value)"></label>`).join('')}</div><p class="fine">Assumes one shared room for your group. Enter additional rooms in the nightly total if needed. A 10% buffer is added. This does not establish real rates for the selected hotel.</p><label class="form-field">Extra / group / day: <b id="extra-value">${money(b.extra)}</b><input aria-label="Extra daily allowance" type="range" min="0" max="3000" step="100" value="${b.extra}" oninput="updateBudget('extra',this.value)"></label><div id="budget-breakdown"></div><button class="text-button" onclick="tune()">Change travellers or ceiling ↗</button></div>`}
function updateBudget(key,value){const allowed=['nightly','arrival','food','local','activities','extra'];if(!allowed.includes(key))return;let n=value===''?null:Number(value);if(n!==null&&(!Number.isFinite(n)||n<0||n>1000000))return;tripState().budget[key]=n;renderBudgetBreakdown();renderSummary()}
function renderBudgetBreakdown(){const el=$('#budget-breakdown');if(!el)return;const v=budgetValues();if($('#extra-value'))$('#extra-value').textContent=money(tripState().budget.extra||0);el.innerHTML=[['Stay',v.stay],['Arrival travel',v.arrival],['Food',v.food],['Local transport',v.local],['Activities',v.activities],['Extras',v.extra],['10% buffer',v.buffer]].map(([n,c])=>`<div class="costline"><span>${n}</span><b>${c===null?'Quote needed':money(c)}</b></div>`).join('')+`<div class="tier picked"><span>${v.complete?'Planning total':'Known allowances only'}</span><b>${money(v.total)}</b></div><p class="fine">${v.complete?(v.total<=budget?'Within your entered ceiling using these assumptions.':'Above your entered ceiling. Adjust assumptions or raise the ceiling before the demo confirmation.'):'Add both the nightly room quote and arrival travel cost to calculate a complete planning total.'}</p>`}
function planIds(){return routeDays().flatMap(d=>d.stops).map(p=>p.id)}
function discoveryCards(s){const memory=routeMemory[s.id];return `<div class="discovery-grid">${stopList(s).filter(p=>!trailOnlySaved||(memory?.saved||[]).includes(p.id)).map((p,i)=>`<article class="discovery-card">${photoFigure(p.photo)}<span class="eyebrow">${escapeHTML(s.base.toUpperCase())} · FIELD NOTE ${String(i+1).padStart(2,'0')}</span><h3>${escapeHTML(p.name)}</h3><p>${escapeHTML(p.why)}</p><div class="place-links">${external(p.source,'Tourism source')}${external(maps(p.mapQuery),'Map')}</div><button class="secondary wide" onclick="saveDiscovery('${s.id}','${p.id}')">${memory?.saved.includes(p.id)?'✓ Saved in this trip':'＋ Save to '+escapeHTML(s.name)+' trip'}</button></article>`).join('')||'<div class="empty-state"><h3>No saved places here yet.</h3><p>Show all places and save one to this state’s trip.</p><button class="primary" onclick="trailOnlySaved=false;renderTrails()">Show all places</button></div>'}</div>`}
function renderTrails(){const s=ALL_ROUTES.find(s=>s.id===trailState)||current();const controls=`<div class="trail-toolbar"><label class="form-field">Explore a state<select aria-label="Trails state" onchange="trailState=this.value;renderTrails()">${ALL_ROUTES.map(r=>`<option value="${r.id}" ${r.id===s.id?'selected':''}>${r.name}</option>`).join('')}</select></label><button class="secondary" onclick="trailOnlySaved=!trailOnlySaved;renderTrails()">${trailOnlySaved?'Show all places':'Saved places'}</button></div>`;$('#trail-grid').className='';$('#trail-grid').innerHTML=controls+`<p class="fine">Sourced place ideas for ${escapeHTML(s.name)}. These are editorial discovery cards, not user reviews.</p>`+discoveryCards(s)+furtherCards(s)}
function saveDiscovery(routeId,placeId){const s=ALL_ROUTES.find(s=>s.id===routeId);if(!s||!stopById(s,placeId))throw new Error('Unknown place');const old=destination;destination=s.name;const m=tripState();if(!m.saved.includes(placeId))m.saved.push(placeId);destination=old;if(!$('#trip').hidden)renderTrip();renderTrails();notify('Saved to the '+s.name+' itinerary. No duplicate stop added.');return {state:s.name,saved:[...m.saved]}}
function pinSpot(id){const m=tripState();if(m.saved.includes(id)){m.saved=m.saved.filter(v=>v!==id);renderTrip();notify('Removed from saved places.')}else saveDiscovery(current().id,id)}
function swapActivity(id){const s=current(),shown=new Set(planIds()),options=stopList(s).filter(p=>!shown.has(p.id));if(!options.length){notify('All researched stops are already in this route. Save fewer extras before swapping.');return}sheet(`<h2>A different kind of afternoon.</h2><p>Choose another researched stop in ${escapeHTML(s.name)}. Recheck the day’s map after swapping.</p>${options.map(p=>`<button class="swap-option" onclick="applySwap('${id}','${p.id}')"><strong>${escapeHTML(p.name)}</strong><span>${escapeHTML(p.why)}</span></button>`).join('')}`)}
function applySwap(oldId,newId){const m=tripState();let original=Object.keys(m.swaps).find(k=>m.swaps[k]===oldId)||oldId;m.swaps[original]=newId;m.saved=m.saved.filter(id=>id!==oldId);$('#sheet').close();renderTrip();notify('Stop swapped. No unverified price change was applied.')}
function book(){const s=current(),v=budgetValues();const ready=v.complete&&v.total<=budget;sheet(`<span class="eyebrow">ONE TRIP. ONE CLEAR YES.</span><h2>${ready?'Review your planned escape.':'A few numbers to confirm.'}</h2><p>${escapeHTML(s.name)} · ${$('#days').value} days · ${escapeHTML(s.hotels[tripState().hotel].name)}</p><div class="tier"><span>${v.complete?'Planning estimate':'Partial worksheet'}</span><b>${money(v.total)}</b></div><p>Ceiling: ${money(budget)}. ${!v.complete?'Add a room quote and arrival travel cost first.':v.total>budget?'The worksheet exceeds your ceiling.':'Your entered assumptions fit the ceiling.'}</p><p>This is a planning demo. Availability, actual charges and cancellation terms must be confirmed with providers. Nothing is reserved or paid.</p>${ready?'<button class="primary wide" onclick="confirmDemo()">Confirm demo trip ✓</button>':'<button class="primary wide" onclick="document.querySelector(\'#sheet\').close();setTab(\'Money\')">Complete the budget worksheet ↗</button>'}`)}
function confirmDemo(){tripState().booked=true;$('#sheet-content').innerHTML=`<span class="eyebrow">ALL TOGETHER NOW</span><h2>Your demo trip is saved. ✓</h2><p>${escapeHTML(current().base)} is on your planning list. No real booking or payment has been made.</p><button class="primary wide" onclick="document.querySelector('#sheet').close();setTab('Go')">Open your travel companion ↗</button>`}
function delay(){sheet(`<span class="eyebrow">WHEN LIFE CHANGES THE PLAN</span><h2>Flight delayed by 2 hours.</h2><p>In this demo, the first sightseeing day’s final stop moves to the following day. A late check-in note would be prepared for ${escapeHTML(current().hotels[tripState().hotel].name)}.</p><p class="fine">This is a simulation. No flight tracking, hotel message or automatic rebooking takes place.</p><button class="primary wide" onclick="tripState().late=true;document.querySelector('#sheet').close();renderTrip();notify('Demo recovery applied. Review the revised route; no message sent.')">Approve the revised day ✓</button>`)}
function togglePacking(i,value){const m=tripState();m.checked=value?[...new Set([...m.checked,i])]:m.checked.filter(v=>v!==i)}
function printTrip(){setTab('Plan');setTimeout(()=>window.print(),50)}
function support(){sheet('<h2>A person, with the full picture.</h2><p>The support flow is a demo. For this trip, use the property’s official contact page for stay questions. No message is sent from Compass.</p>'+external(current().hotels[tripState().hotel].url,'Open the stay’s contact website','secondary'))}
function post(){sheet(`<span class="eyebrow">FOUND SOMETHING GOOD?</span><h2>Put it on the map.</h2><label class="form-field">Place name<input id="place-name" placeholder="The little homestay you almost missed" required maxlength="100"></label><label class="form-field">Your field note<textarea id="caption" rows="2" placeholder="What made it worth the detour?" maxlength="500"></textarea></label><label class="form-field">Photo<input type="file" accept="image/*"></label><label class="form-field">Trip month<input type="month" id="trip-month" value="2026-09"></label><button class="primary wide" onclick="submitPost()">Add sample discovery ↗</button><p class="fine">Session-only demo. Nothing is published publicly.</p>`)}
function submitPost(){const name=$('#place-name').value.trim();if(!name){$('#place-name').focus();notify('Give this place a name first.');return}queue.push({name,caption:$('#caption').value.trim()});$('#sheet').close();supply()}
function supply(){sheet(`<span class="eyebrow">COMMUNITY → NEW PLACES TO STAY</span><h2>The next great find.</h2><p>New discoveries enter moderation. Three distinct traveller contributions are needed before a place can be verified for supply review.</p>${queue.length?queue.map(p=>`<div class="panel"><h3>${escapeHTML(p.name)}</h3><p>${escapeHTML(p.caption)}</p><span class="mini-badge">Candidate · 1 of 3 contributors · Awaiting moderation</span></div>`).join(''):'<p>No discoveries yet. Share a place to see it enter the sample queue.</p><button class="primary" onclick="document.querySelector(\'#sheet\').close();post()">Share the first discovery</button>'}`)}
function voice(){const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech){notify('Voice isn’t supported here. Type your idea instead.');$('#intent').focus();return}const r=new Speech();r.lang='en-IN';r.onresult=e=>{$('#intent').value=e.results[0][0].transcript;notify('Got it. Ready when you are.')};r.onerror=()=>notify('Couldn’t hear you. Try typing your idea.');r.start();notify('Listening for your next escape…')}
$('#photo').onchange=()=>{if($('#photo').files.length)sheet('<h2>A picture is a good start.</h2><p>Photo recognition isn’t connected in this prototype. Add the place name or describe the scenery in the planner to try a sample trip.</p><button class="primary wide" onclick="document.querySelector(\'#sheet\').close();document.querySelector(\'#intent\').focus()">Describe this escape ↗</button>')};
// Optional agent interface uses the same validated state as the visible controls.
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'save_discovery_to_sample_trip',description:'Save a researched place to its own Indian-state itinerary. Does not reserve travel.',inputSchema:{type:'object',properties:{state:{type:'string',enum:ALL_ROUTES.map(s=>s.name)},place:{type:'string'}},required:['state','place'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:({state,place})=>{const s=stateByName(state),p=s&&stopList(s).find(p=>p.name===place);if(!p)throw new Error('Unknown state or place');return saveDiscovery(s.id,p.id)}})}catch(e){console.info('Optional agent tools unavailable')}}
const originalRenderTrip=renderTrip;renderTrip=function(){originalRenderTrip();renderBudgetBreakdown()};
window.addEventListener('hashchange',loadTripHash);
renderTrails();loadTripHash();

function aiInfo(){sheet(`<span class="eyebrow">AI & THIS PROTOTYPE</span><h2>What is actually intelligent here?</h2><div class="panel"><h3>Today: a curated planner</h3><p>Typed destinations are matched to researched routes using keywords. Duration changes, saved places, budgets and delay recovery follow fixed rules. No language model generates or personalises this itinerary.</p></div><div class="panel"><h3>Voice & agent access</h3><p>Voice uses your browser’s speech-recognition service when supported. An optional browser tool lets a compatible external agent save a researched place; it is not an AI model inside Compass.</p></div><div class="panel"><h3>What connected AI could add</h3><p>Understand open-ended requests, recognise destinations in photos, explain trade-offs, and rebuild a feasible route around your interests. Those features would need a model connection plus current travel data and route checks. They are not active here.</p></div><p class="fine">Photos are real destination images. Hotel and food links are references, not live availability. Booking and flight recovery remain demonstrations.</p>`)}

function photoCredit(p){return p?external(p.source,`${p.credit} · ${p.license} · Photo & license`,'photo-credit'):''}
function photoFigure(p,cls='place-photo'){return p?`<figure class="${cls}"><img src="${escapeHTML(p.url)}" alt="${escapeHTML(p.caption)}" loading="lazy" width="960" height="600"><figcaption>${escapeHTML(p.caption)}<br>${photoCredit(p)}</figcaption></figure>`:''}
function furtherCards(s){const list=s.further||[];if(!list.length)return '';return `<section class="further-section"><span class="eyebrow">MORE OF ${escapeHTML(s.name.toUpperCase())}</span><h2>Beyond the city route.</h2><p>These ideas need a separately planned outing or stay. They are not automatically added to your city itinerary.</p><div class="discovery-grid">${list.map(p=>`<article class="discovery-card">${photoFigure(p.photo)}<span class="mini-badge">Plan separately</span><h3>${escapeHTML(p.name)}</h3><p>${escapeHTML(p.why)}</p><div class="place-links">${external(p.source,'Explore tourism guide')}${external(maps(p.name+', '+s.name+', India'),'View on map')}</div></article>`).join('')}</div></section>`}
function renderFood(s){const selected=tripState().meals||[];return `<div class="route-intro"><span class="eyebrow">A TABLE WORTH FINDING</span><h2>Eat around ${escapeHTML(s.base)}.</h2><p>Named food spots with venue or tourism sources. Check current menus, prices, dietary requirements and opening hours before visiting.</p>${s.name==='Manipur'?'<p class="route-note advisory">Reference collection only. Review the current Manipur travel advisory before making plans.</p>':''}</div><div class="food-grid">${(s.food||[]).map((f,i)=>`<article class="panel food-card"><span class="eyebrow">${escapeHTML(f.kind)}</span><h2>${escapeHTML(f.name)}</h2><p class="food-cuisine">${escapeHTML(f.cuisine)}</p><p>⌖ ${escapeHTML(f.area)}</p><div class="place-links">${external(f.url,'Venue / menu source')}${external(maps(f.name+', '+f.area+', India'),'Find on map')}</div><button class="secondary wide" onclick="toggleMeal(${i})">${selected.includes(i)?'✓ On your food shortlist':'＋ Add to food shortlist'}</button></article>`).join('')}</div><p class="fine">Your shortlist lasts for this session. Saving a food spot does not reserve a table, change sightseeing times, or add a quoted meal price to the budget.</p>`}
function toggleMeal(i){const m=tripState();m.meals=m.meals||[];m.meals=m.meals.includes(i)?m.meals.filter(x=>x!==i):[...m.meals,i];renderTrip()}

function openStateCard(name){const s=stateByName(name),q=$('#state-search').value.trim().toLowerCase();choose(name);if(q&&(s.further||[]).some(p=>p.name.toLowerCase().includes(q))){setTab('Trails');document.querySelector('#trip-content .further-section').scrollIntoView({behavior:'smooth'})}else if(q&&(s.food||[]).some(p=>p.name.toLowerCase().includes(q)))setTab('Food');else if(q&&s.hotels.some(h=>h.name.toLowerCase().includes(q)))setTab('Stay')}
